### ISSUE TITLE
Open file problem

### ISSUE THREAD

**Issue by makersm** [makerj/dev#1]
When I open the file using double-click icon, automatically open with VIM, then get error.

How to fix it? help!

**Comment by makerj** [comment]
Tell me specifically what error you are experiencing

**Comment by makersm** [comment]
I open the cpp code with double click icon in folder(and automatically open with GVim), and gets stuck.
after few trial, the code are opened well, but sometimes code closed when I open it.

**Comment by makerj** [comment]
I'll figure out that. As a temporary measure, please change the default program to Vim instead of GVim
